/* MOCK DATA - replace via api.js once the Java backend is connected. */
const LOREM_ML = "Machine learning is a field of artificial intelligence that lets systems learn patterns from data instead of following fixed rules. Supervised learning trains on labelled examples, while unsupervised learning finds structure in unlabelled data. Search engines use machine learning to rank documents, and modern indexing pipelines combine it with classic string matching.";
const DOCS = [
    {id:1,title:"Machine Learning Fundamentals",type:"PDF",category:"Research",date:"2026-08-14",pages:42,text:LOREM_ML+"\n\nModel evaluation relies on held-out data. Precision, recall and F1 score summarise how well a classifier performs. Overfitting occurs when a model memorises training data, so regularisation and cross-validation are used to keep machine learning models general."},
    {id:2,title:"String Matching Algorithms: KMP and Rabin-Karp",type:"PDF",category:"Algorithms",date:"2026-07-30",pages:18,text:"The Knuth-Morris-Pratt algorithm preprocesses the pattern into a failure table so the text pointer never moves backwards, giving O(n + m) exact search. Rabin-Karp uses a rolling hash to compare windows of text with the pattern hash, and is well suited to searching many patterns of equal length.\n\nThe Z algorithm computes, for each position, the longest substring starting there that matches a prefix of the string. It solves pattern search in linear time by concatenating pattern, separator and text."},
    {id:3,title:"Enterprise Data Retention Policy",type:"DOCX",category:"Compliance",date:"2026-09-02",pages:9,text:"This policy defines how long enterprise records are stored, who may access archived documents, and how deletion requests are handled. Financial records are retained for seven years. Employee data is retained for the duration of employment plus two years. Every retention exception must be approved by the compliance office."},
    {id:4,title:"Cloud Migration Runbook",type:"TXT",category:"Engineering",date:"2026-09-11",pages:6,text:"Step 1: freeze schema changes. Step 2: replicate the primary database to the cloud region. Step 3: switch read traffic and monitor latency. Rollback is triggered when error rate exceeds one percent. Search indexes are rebuilt after migration so document search stays consistent."},
    {id:5,title:"Aho-Corasick for Multi-Pattern Search",type:"PDF",category:"Algorithms",date:"2026-06-21",pages:24,text:"Aho-Corasick builds a trie of all patterns and adds failure links, so the whole text is scanned once while every pattern is matched at the same time. It is the standard choice for keyword filtering, virus signature scanning and enterprise search with many query terms.\n\nSuffix arrays and LCP arrays support fast substring queries after an O(n log n) build, at the cost of extra memory."},
    {id:6,title:"Quarterly Security Audit Report",type:"DOCX",category:"Security",date:"2026-08-28",pages:31,text:"The audit reviewed access controls, encryption at rest and incident response. Two findings were rated high: shared service accounts and missing log retention. Remediation owners were assigned and the next security audit is scheduled for the following quarter."},
    {id:7,title:"Customer Support Knowledge Base Export",type:"TXT",category:"Support",date:"2026-09-15",pages:120,text:"How to reset a password. How to update billing details. Troubleshooting slow search results: check the index status, clear the cache and confirm the document count. Common typos in customer queries are handled with edit distance so that 'serach' still finds 'search'."},
    {id:8,title:"Distributed Systems Lecture Notes",type:"PDF",category:"Education",date:"2026-05-12",pages:57,text:"Consensus protocols allow nodes to agree on a value despite failures. Parallel search splits the document collection across worker threads, each running the same algorithm on its own shard, and merges the ranked results at the end. Speedup depends on how evenly the documents are partitioned."}
];
const ALGOS = [
    {name:"Naive Search",purpose:"Compare the pattern at every text position; simplest baseline.",time:"O(n·m)",use:"Baseline for benchmarking and very short texts."},
    {name:"KMP",purpose:"Uses a failure table to skip re-comparisons.",time:"O(n + m)",use:"Default for single-pattern exact search."},
    {name:"Rabin-Karp",purpose:"Compares rolling hashes of text windows.",time:"O(n + m) avg",use:"Equal-length multi-pattern search and plagiarism checks."},
    {name:"Z Algorithm",purpose:"Computes prefix-match lengths for every position.",time:"O(n + m)",use:"Fast exact search with pattern-prefix reuse."},
    {name:"Aho-Corasick",purpose:"Trie with failure links matches many patterns in one pass.",time:"O(n + m + z)",use:"Multi-word queries and keyword filtering."},
    {name:"Suffix Array",purpose:"Sorted array of all suffixes enabling binary-search lookups.",time:"O(n log n) build",use:"Repeated substring queries on a large indexed corpus."},
    {name:"LCP Array",purpose:"Longest common prefix between adjacent suffixes.",time:"O(n) build",use:"Finds repeated phrases and speeds up suffix array queries."},
    {name:"Edit Distance",purpose:"Minimum edits to turn one string into another (DP).",time:"O(n·m)",use:"Typo-tolerant suggestions and fuzzy matching."},
    {name:"Parallel Search",purpose:"Splits documents across threads and merges results.",time:"O(T / p)",use:"Large collections; runs any algorithm per shard."}
];
const POPULAR = ["machine learning","data retention policy","security audit","KMP algorithm","cloud migration"];
const BENCH = {docsSearched:12480,algorithms:[
        {name:"Naive Search",time:48.2,matches:127,avg:46.9},{name:"KMP",time:18.2,matches:127,avg:17.6},
        {name:"Rabin-Karp",time:21.7,matches:127,avg:20.9},{name:"Z Algorithm",time:17.4,matches:127,avg:17.1},
        {name:"Aho-Corasick",time:12.9,matches:214,avg:12.4}],
    scaling:{sizes:[1000,2500,5000,10000,12480],series:{"Naive Search":[4,10,20,39,48],"KMP":[1.5,4,8,15,18],"Aho-Corasick":[1,3,6,10,13]}}};